
# This Dockerfile is designed for production, not development. Use with Kamal or build'n'run by hand:
# docker build -t floss_playground .
# docker run -d -p 80:80 -e RAILS_MASTER_KEY=<value from config/master.key> --name floss_playground floss_playground

# For a containerized dev environment, see Dev Containers: https://guides.rubyonrails.org/getting_started_with_devcontainer.html

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
FROM ruby:3.3 AS base

# Rails app lives here
WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives




