scrape_configs:
  - job_name: cat-ruby
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:9464"]
  - job_name: another
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus-exporter:9394"]